summary: ''
description: ''
lock: '!inline f/domains/work/infra/refresh_sdp_token.script.lock'
kind: script
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: object
  properties: {}
  required: []
