summary: ''
description: ''
lock: '!inline f/devops/aikido_trigger_scan.script.lock'
kind: script
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: object
  properties:
    repo_id:
      type: string
      description: ''
      default: null
      originalType: string
  required:
    - repo_id
