summary: ''
description: ''
lock: '!inline f/devops/compliance_scan.script.lock'
kind: script
schema:
  $schema: https://json-schema.org/draft/2020-12/schema
  type: object
  properties:
    benchmark:
      type: string
      description: ''
      default: ''
      originalType: string
    format:
      type: string
      description: ''
      default: json
      originalType: string
  required: []
