#!/usr/bin/env bash
# aws-accounts-config.sh - Generate ~/.aws/config from BWS secret
# Reads aws-cross-accounts JSON from BWS and generates AWS CLI profiles
set -euo pipefail

# Source bws-init for helper functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "$SCRIPT_DIR/bws-init.sh" ]]; then
    source "$SCRIPT_DIR/bws-init.sh"
elif [[ -f "$HOME/bin/bws-init" ]]; then
    source "$HOME/bin/bws-init"
fi

AWS_CONFIG="$HOME/.aws/config"
BWS_SECRET="aws-cross-accounts"

log() { echo "[aws-config] $*"; }
log_success() { echo "[aws-config] ✓ $*"; }
log_error() { echo "[aws-config] ✗ $*" >&2; }

show_help() {
    cat << 'EOF'
Usage: aws-accounts-config [COMMAND]

Generate ~/.aws/config from BWS secret 'aws-cross-accounts'.

Commands:
  generate    Generate/update ~/.aws/config (default)
  list        List configured accounts (from BWS)
  test        Test access to all configured accounts
  add         Add a new account interactively
  help        Show this help

Secret Format (JSON array in BWS):
  [
    {
      "id": "111111111111",
      "name": "org-dev",
      "roles": ["ReadOnlyAccess", "AdministratorAccess"],
      "purpose": "Development environment"
    }
  ]

Generated Profile Names:
  [profile org-dev-readonly]     (for ReadOnlyAccess role)
  [profile org-dev-admin]        (for AdministratorAccess role)

Examples:
  aws-accounts-config              # Generate config
  aws-accounts-config list         # Show accounts
  aws-accounts-config test         # Verify access
  aws --profile org-dev-readonly s3 ls
EOF
}

# Get accounts JSON from BWS
get_accounts() {
    local accounts
    accounts=$(bws_get "$BWS_SECRET" 2>/dev/null) || {
        log_error "Secret '$BWS_SECRET' not found in BWS"
        log_error "Create it with: bws_set '$BWS_SECRET' '<json>'"
        return 1
    }

    # Validate JSON
    if ! echo "$accounts" | jq empty 2>/dev/null; then
        log_error "Invalid JSON in '$BWS_SECRET'"
        return 1
    fi

    echo "$accounts"
}

# Map role name to profile suffix
role_to_suffix() {
    local role="$1"
    case "$role" in
        ReadOnlyAccess) echo "readonly" ;;
        AdministratorAccess) echo "admin" ;;
        PowerUserAccess) echo "poweruser" ;;
        ViewOnlyAccess) echo "viewonly" ;;
        *) echo "${role,,}" ;;  # lowercase
    esac
}

# Generate ~/.aws/config
generate_config() {
    local accounts
    accounts=$(get_accounts) || return 1

    # Backup existing config
    if [[ -f "$AWS_CONFIG" ]]; then
        cp "$AWS_CONFIG" "${AWS_CONFIG}.bak"
        log "Backed up existing config to ${AWS_CONFIG}.bak"
    fi

    mkdir -p "$(dirname "$AWS_CONFIG")"

    # Start with header
    cat > "$AWS_CONFIG" << 'EOF'
# AWS CLI Config - Generated by aws-accounts-config
# Source: BWS secret 'aws-cross-accounts'
# Regenerate: aws-accounts-config generate

[default]
region = us-east-1
output = json

EOF

    # Generate profiles for each account/role combo
    local count=0
    while IFS= read -r account; do
        local id name purpose
        id=$(echo "$account" | jq -r '.id')
        name=$(echo "$account" | jq -r '.name')
        purpose=$(echo "$account" | jq -r '.purpose // ""')

        # Add comment for account
        echo "# $name - $purpose" >> "$AWS_CONFIG"

        # Generate profile for each role
        while IFS= read -r role; do
            local suffix profile_name
            suffix=$(role_to_suffix "$role")
            profile_name="${name}-${suffix}"

            cat >> "$AWS_CONFIG" << EOF
[profile $profile_name]
role_arn = arn:aws:iam::${id}:role/${role}
credential_source = Ec2InstanceMetadata
region = us-east-1

EOF
            ((count++))
        done < <(echo "$account" | jq -r '.roles[]')

    done < <(echo "$accounts" | jq -c '.[]')

    log_success "Generated $count profiles in $AWS_CONFIG"
}

# List accounts from BWS
list_accounts() {
    local accounts
    accounts=$(get_accounts) || return 1

    echo ""
    echo "AWS Cross-Account Access (from BWS)"
    echo "===================================="
    echo ""

    echo "$accounts" | jq -r '.[] | "Account: \(.id)\n  Name: \(.name)\n  Purpose: \(.purpose // "N/A")\n  Roles: \(.roles | join(", "))\n"'

    echo ""
    echo "Profile names:"
    while IFS= read -r account; do
        local name
        name=$(echo "$account" | jq -r '.name')
        while IFS= read -r role; do
            local suffix
            suffix=$(role_to_suffix "$role")
            echo "  ${name}-${suffix}"
        done < <(echo "$account" | jq -r '.roles[]')
    done < <(echo "$accounts" | jq -c '.[]')
}

# Test access to all accounts
test_accounts() {
    local accounts
    accounts=$(get_accounts) || return 1

    echo ""
    echo "Testing AWS Cross-Account Access"
    echo "================================="
    echo ""

    local success=0 failed=0

    while IFS= read -r account; do
        local name
        name=$(echo "$account" | jq -r '.name')

        while IFS= read -r role; do
            local suffix profile_name
            suffix=$(role_to_suffix "$role")
            profile_name="${name}-${suffix}"

            printf "  %-30s " "$profile_name"

            if aws --profile "$profile_name" sts get-caller-identity &>/dev/null; then
                echo "✓ OK"
                ((success++))
            else
                echo "✗ FAILED"
                ((failed++))
            fi
        done < <(echo "$account" | jq -r '.roles[]')

    done < <(echo "$accounts" | jq -c '.[]')

    echo ""
    echo "Results: $success passed, $failed failed"

    [[ $failed -eq 0 ]]
}

# Add account interactively
add_account() {
    echo ""
    echo "Add AWS Cross-Account"
    echo "====================="
    echo ""

    read -p "Account ID (12 digits): " id
    read -p "Account name (e.g., org-dev): " name
    read -p "Purpose/description: " purpose

    echo ""
    echo "Available role templates:"
    echo "  1) ReadOnlyAccess"
    echo "  2) AdministratorAccess"
    echo "  3) Both (readonly + admin)"
    echo "  4) Custom"
    read -p "Select [1-4]: " role_choice

    local roles
    case "$role_choice" in
        1) roles='["ReadOnlyAccess"]' ;;
        2) roles='["AdministratorAccess"]' ;;
        3) roles='["ReadOnlyAccess", "AdministratorAccess"]' ;;
        4)
            read -p "Role names (comma-separated): " custom_roles
            roles=$(echo "$custom_roles" | jq -R 'split(",") | map(gsub("^\\s+|\\s+$"; ""))')
            ;;
        *) log_error "Invalid choice"; return 1 ;;
    esac

    # Build new account JSON
    local new_account
    new_account=$(jq -n \
        --arg id "$id" \
        --arg name "$name" \
        --arg purpose "$purpose" \
        --argjson roles "$roles" \
        '{id: $id, name: $name, purpose: $purpose, roles: $roles}')

    echo ""
    echo "New account:"
    echo "$new_account" | jq .
    echo ""
    read -p "Add this account? [y/N] " confirm

    if [[ "${confirm:-n}" =~ ^[Yy]$ ]]; then
        local accounts
        accounts=$(get_accounts 2>/dev/null || echo "[]")

        # Append new account
        local updated
        updated=$(echo "$accounts" | jq --argjson new "$new_account" '. + [$new]')

        # Save to BWS
        bws_set "$BWS_SECRET" "$updated"
        log_success "Account added to BWS"

        # Regenerate config
        generate_config
    else
        log "Cancelled"
    fi
}

# Main
case "${1:-generate}" in
    generate) generate_config ;;
    list) list_accounts ;;
    test) test_accounts ;;
    add) add_account ;;
    help|--help|-h) show_help ;;
    *) log_error "Unknown command: $1"; show_help; exit 1 ;;
esac
